"""add unique Song constraint

Revision ID: 60b3d55e8b8a
Revises: dfa094b6cbb5
Create Date: 2024-05-18 19:07:40.494097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b3d55e8b8a'
down_revision = 'dfa094b6cbb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_artist_album_track', ['artist_name', 'album_name', 'track_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artist_album_track', type_='unique')

    # ### end Alembic commands ###
