"""unique constraint on admin username

Revision ID: 7ec8ea8bb85a
Revises: 27cfa8f137c9
Create Date: 2024-05-21 20:43:42.877471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec8ea8bb85a'
down_revision = '27cfa8f137c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')

    # ### end Alembic commands ###
