"""Initial migration.

Revision ID: b660502d3e84
Revises: 
Create Date: 2024-05-19 17:46:39.116390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b660502d3e84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_genre')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('happy', sa.Float(), nullable=False),
    sa.Column('aggressive', sa.Float(), nullable=False),
    sa.Column('sad', sa.Float(), nullable=False),
    sa.Column('calm', sa.Float(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('album_cover_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_name', 'album_name', 'track_name', name='uq_artist_album_track')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_aggressive'), ['aggressive'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_calm'), ['calm'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_happy'), ['happy'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_sad'), ['sad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_sad'))
        batch_op.drop_index(batch_op.f('ix_song_happy'))
        batch_op.drop_index(batch_op.f('ix_song_calm'))
        batch_op.drop_index(batch_op.f('ix_song_aggressive'))

    op.drop_table('song')
    op.drop_table('genre')
    op.drop_table('admin')
    # ### end Alembic commands ###
