"""album_cover_url support

Revision ID: dfa094b6cbb5
Revises: 2bc6d7897c8a
Create Date: 2024-05-18 17:19:48.850369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfa094b6cbb5'
down_revision = '2bc6d7897c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_cover_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('album_cover_url')

    # ### end Alembic commands ###
