"""unique genre constraint

Revision ID: e1fdbe7adf3f
Revises: 60b3d55e8b8a
Create Date: 2024-05-18 19:23:29.741612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1fdbe7adf3f'
down_revision = '60b3d55e8b8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_genre', ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_constraint('uq_genre', type_='unique')

    # ### end Alembic commands ###
