"""add table song, genre

Revision ID: f158861b9182
Revises: 
Create Date: 2024-04-22 21:51:55.941530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f158861b9182'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('album_name', sa.String(length=255), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('happy', sa.Float(), nullable=False),
    sa.Column('aggressive', sa.Float(), nullable=False),
    sa.Column('sad', sa.Float(), nullable=False),
    sa.Column('calm', sa.Float(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_song_aggressive'), ['aggressive'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_calm'), ['calm'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_happy'), ['happy'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_sad'), ['sad'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_sad'))
        batch_op.drop_index(batch_op.f('ix_song_happy'))
        batch_op.drop_index(batch_op.f('ix_song_calm'))
        batch_op.drop_index(batch_op.f('ix_song_aggressive'))

    op.drop_table('song')
    op.drop_table('genre')
    # ### end Alembic commands ###
